### PR TITLE
All recent edits and updates (to media-relative-refs)

### PR DESCRIPTION
**Pull request by Serg-Norseman**

### CODE REVIEW

**Comment by Serg-Norseman** [comment]
You deleted this line by mistake:

`fView.StoreType.SetSelectedTag<MediaStoreType>(selectType);`

**Comment by m-kosina** [comment]
I know, sorry for this - I noticed it immediatelly (the merging is done differently, that I used to do in Subversion), so I already push the fix

**Comment by m-kosina** [comment]
And I also already tested that it works on my data :)

**Comment by Serg-Norseman** [comment]
I also made a not bad, but strange mistake: while I checked the course of actions for the merger for you, I accidentally merged your branch and my `master`. I apologize, I accepted your changes without a full discussion and until the final proofreading. How I did it, I don’t understand ...

**Comment by Serg-Norseman** [comment]
But this is not scary, now I have to accept both your last edit and your changes will now be fully included in the main project. Congratulations on your first commits to the project!

**Comment by m-kosina** [comment]
Thank you :). I'm not 100% friend of GitHub yet :(, so please just tell me - how should I continue now - imo I should merge my branch with my master - and then update it from your master? For this I should specify upstream repository? ...

**Comment by Serg-Norseman** [comment]
First, just in case, take in your master branch, the first pull request from me (https://github.com/m-kosina/GEDKeeper/pull/1). Then, if everything is tested for you and works as it should, combine the feature branch and your master. And then you can send your first pull request from your repository to my master.

**Pull request merged**
